version: '2.0'

services:

  mysql:
    env_file:
      - ./.env
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 9002:3306
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSUSER}
      MYSQL_ROOT_PASSWORD: ${PASSROOT}
    restart: always 
    volumes:
      - ${PWD}/docker/mysql:/var/lib/mysql
      - ${PWD}/sql:/var/local

  web:
    build: ./docker/php
    ports:
      - 9000:80
    volumes:
      - ${PWD}/app:/var/www/html
    links:
      - mysql
